services:
  api-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - product-service
      - order-service

  product-service:
    image: practice-microservices/product-service:latest
    container_name: product-service
    ports:
      - "50051:50051"

  order-service:
    image: practice-microservices/order-service:latest
    container_name: order-service
    ports:
      - "50052:50052"